export const SET_INITIAL_SPORTS_STATE = 'SET_INITIAL_SPORTS_STATE';
export const CHANGE_SPORTS_STATE = 'CHANGE_SPORTS_STATE';
export const CHANGE_USER_STATE = 'CHANGE_USER_STATE';
export const CHANGE_USER_SPORTS_STATE = 'CHANGE_USER_SPORTS_STATE';


