export const SET_INITIAL_SPORTS_STATE = 'SET_INITIAL_SPORTS_STATE';
export const CHANGE_SPORTS_STATE = 'CHANGE_SPORTS_STATE';
export const CHANGE_USER_STATE = 'CHANGE_USER_STATE';
export const CHANGE_USER_BETS_STATE = 'CHANGE_USER_BETS_STATE';
export const UPDATE_BET_STATE = 'UPDATE_BET_STATE';
export const REMOVE_BET = 'REMOVE_BET';
export const ADD_BET = 'ADD_BET';
export const SET_ERROR_STATE = 'SET_ERROR_STATE';


